/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__heading_marker = 1,
  sym__heading_text = 2,
  sym_heading_bracket = 3,
  sym__heading_eol = 4,
  sym_code_line = 5,
  sym_language_switch = 6,
  sym_transclusion = 7,
  sym_prose_line = 8,
  sym_blank_line = 9,
  sym_document = 10,
  sym_heading = 11,
  sym_code_block = 12,
  sym_prose_block = 13,
  aux_sym_document_repeat1 = 14,
  aux_sym_code_block_repeat1 = 15,
  aux_sym_prose_block_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__heading_marker] = "_heading_marker",
  [sym__heading_text] = "_heading_text",
  [sym_heading_bracket] = "heading_bracket",
  [sym__heading_eol] = "_heading_eol",
  [sym_code_line] = "code_line",
  [sym_language_switch] = "language_switch",
  [sym_transclusion] = "transclusion",
  [sym_prose_line] = "prose_line",
  [sym_blank_line] = "blank_line",
  [sym_document] = "document",
  [sym_heading] = "heading",
  [sym_code_block] = "code_block",
  [sym_prose_block] = "prose_block",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_code_block_repeat1] = "code_block_repeat1",
  [aux_sym_prose_block_repeat1] = "prose_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__heading_marker] = sym__heading_marker,
  [sym__heading_text] = sym__heading_text,
  [sym_heading_bracket] = sym_heading_bracket,
  [sym__heading_eol] = sym__heading_eol,
  [sym_code_line] = sym_code_line,
  [sym_language_switch] = sym_language_switch,
  [sym_transclusion] = sym_transclusion,
  [sym_prose_line] = sym_prose_line,
  [sym_blank_line] = sym_blank_line,
  [sym_document] = sym_document,
  [sym_heading] = sym_heading,
  [sym_code_block] = sym_code_block,
  [sym_prose_block] = sym_prose_block,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_code_block_repeat1] = aux_sym_code_block_repeat1,
  [aux_sym_prose_block_repeat1] = aux_sym_prose_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__heading_marker] = {
    .visible = false,
    .named = true,
  },
  [sym__heading_text] = {
    .visible = false,
    .named = true,
  },
  [sym_heading_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym__heading_eol] = {
    .visible = false,
    .named = true,
  },
  [sym_code_line] = {
    .visible = true,
    .named = true,
  },
  [sym_language_switch] = {
    .visible = true,
    .named = true,
  },
  [sym_transclusion] = {
    .visible = true,
    .named = true,
  },
  [sym_prose_line] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_prose_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prose_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bracket = 1,
  field_marker = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bracket] = "bracket",
  [field_marker] = "marker",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
    {field_text, 1},
  [2] =
    {field_bracket, 2},
    {field_marker, 0},
    {field_text, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(sym__heading_text);
      if (eof) ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[') ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '[') ADVANCE(23);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == ']') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(30);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__heading_marker);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__heading_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_heading_bracket);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__heading_eol);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__heading_eol);
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__heading_eol);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '[') ADVANCE(7);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_code_line);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_code_line);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == ']') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_code_line);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_code_line);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_code_line);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_code_line);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_code_line);
      if (lookahead == '\n') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_code_line);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_language_switch);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_language_switch);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_transclusion);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_transclusion);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_prose_line);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_prose_line);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 15},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__heading_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(12),
    [sym_heading] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_prose_block] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_code_block_repeat1] = STATE(4),
    [aux_sym_prose_block_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__heading_marker] = ACTIONS(5),
    [sym_code_line] = ACTIONS(7),
    [sym_language_switch] = ACTIONS(9),
    [sym_transclusion] = ACTIONS(9),
    [sym_prose_line] = ACTIONS(11),
    [sym_blank_line] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_heading] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_prose_block] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_code_block_repeat1] = STATE(4),
    [aux_sym_prose_block_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym__heading_marker] = ACTIONS(5),
    [sym_code_line] = ACTIONS(7),
    [sym_language_switch] = ACTIONS(15),
    [sym_transclusion] = ACTIONS(15),
    [sym_prose_line] = ACTIONS(11),
    [sym_blank_line] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_heading] = STATE(3),
    [sym_code_block] = STATE(3),
    [sym_prose_block] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_code_block_repeat1] = STATE(4),
    [aux_sym_prose_block_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym__heading_marker] = ACTIONS(19),
    [sym_code_line] = ACTIONS(22),
    [sym_language_switch] = ACTIONS(25),
    [sym_transclusion] = ACTIONS(25),
    [sym_prose_line] = ACTIONS(28),
    [sym_blank_line] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(33), 1,
      sym_code_line,
    STATE(6), 1,
      aux_sym_code_block_repeat1,
    ACTIONS(31), 6,
      ts_builtin_sym_end,
      sym__heading_marker,
      sym_language_switch,
      sym_transclusion,
      sym_prose_line,
      sym_blank_line,
  [15] = 4,
    ACTIONS(37), 1,
      sym_code_line,
    ACTIONS(39), 1,
      sym_prose_line,
    STATE(7), 1,
      aux_sym_prose_block_repeat1,
    ACTIONS(35), 5,
      ts_builtin_sym_end,
      sym__heading_marker,
      sym_language_switch,
      sym_transclusion,
      sym_blank_line,
  [32] = 3,
    ACTIONS(43), 1,
      sym_code_line,
    STATE(6), 1,
      aux_sym_code_block_repeat1,
    ACTIONS(41), 6,
      ts_builtin_sym_end,
      sym__heading_marker,
      sym_language_switch,
      sym_transclusion,
      sym_prose_line,
      sym_blank_line,
  [47] = 4,
    ACTIONS(48), 1,
      sym_code_line,
    ACTIONS(50), 1,
      sym_prose_line,
    STATE(7), 1,
      aux_sym_prose_block_repeat1,
    ACTIONS(46), 5,
      ts_builtin_sym_end,
      sym__heading_marker,
      sym_language_switch,
      sym_transclusion,
      sym_blank_line,
  [64] = 2,
    ACTIONS(55), 1,
      sym_code_line,
    ACTIONS(53), 6,
      ts_builtin_sym_end,
      sym__heading_marker,
      sym_language_switch,
      sym_transclusion,
      sym_prose_line,
      sym_blank_line,
  [76] = 2,
    ACTIONS(59), 1,
      sym_code_line,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      sym__heading_marker,
      sym_language_switch,
      sym_transclusion,
      sym_prose_line,
      sym_blank_line,
  [88] = 2,
    ACTIONS(61), 1,
      sym_heading_bracket,
    ACTIONS(63), 1,
      sym__heading_eol,
  [95] = 1,
    ACTIONS(65), 1,
      sym__heading_text,
  [99] = 1,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
  [103] = 1,
    ACTIONS(69), 1,
      sym__heading_eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 15,
  [SMALL_STATE(6)] = 32,
  [SMALL_STATE(7)] = 47,
  [SMALL_STATE(8)] = 64,
  [SMALL_STATE(9)] = 76,
  [SMALL_STATE(10)] = 88,
  [SMALL_STATE(11)] = 95,
  [SMALL_STATE(12)] = 99,
  [SMALL_STATE(13)] = 103,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose_block, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prose_block, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_block_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prose_block_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_prose_block_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prose_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 1),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 4, 0, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [67] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_loom(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "loom",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
