/**
 * Weave engine — materialise `.literate/LITERATE.md` from the
 * vendored Trope/Concept tree plus consumer extensions.
 *
 * Mechanical and deterministic per ADR-025 §2: no AI reasoning,
 * inputs-only, idempotent. Reads the manifest to know what's
 * vendored; reads `.literate/extensions/` for consumer additions;
 * validates each vendored Trope's authored prose against the
 * Trope's `proseSchema` (P3); writes `.literate/LITERATE.md`
 * atomically with the sigil from ADR-024 §3.
 *
 * Per ADR-028 the weave program composes via `Effect.gen`,
 * requires `ManifestService`, and surfaces errors on a tagged
 * channel (`ProseSchemaViolations`, `WeaveIOError`,
 * `ManifestReadError`). Prose-schema validation is collected
 * across all Tropes (no short-circuit) and raised as a single
 * `ProseSchemaViolations` *before* any file write.
 */
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { Context, Data, Effect, Either, Layer, Schema } from 'effect'
import remarkDirective from 'remark-directive'
import remarkMdx from 'remark-mdx'
import remarkParse from 'remark-parse'
import { unified } from 'unified'

import { type AnyTrope } from '@literate/core'

import {
  sessionEndTrope,
  sessionStartTrope,
} from '../trope-bindings.ts'
import {
  ManifestService,
  type ManifestEntry,
  type SeedKind,
} from '../registry/manifest.ts'
import {
  ManifestReadError,
  WeaveIOError,
} from '../errors.ts'

export interface WeaveResult {
  readonly literateMdPath: string
  readonly tropesIncluded: ReadonlyArray<string>
  readonly conceptsIncluded: ReadonlyArray<string>
  readonly extensionsIncluded: ReadonlyArray<string>
}

export interface ProseSchemaViolation {
  readonly _tag: 'ProseSchemaViolation'
  readonly tropeId: string
  readonly path: string
  readonly expected: string
  readonly got: string
}

export class ProseSchemaViolations extends Data.TaggedError(
  'ProseSchemaViolations',
)<{
  readonly violations: ReadonlyArray<ProseSchemaViolation>
}> {
  override get message(): string {
    const body = this.violations
      .map((v) => `  - ${v.tropeId} (${v.path}): ${v.got}`)
      .join('\n')
    return `weave: prose-schema validation failed for ${this.violations.length} Trope(s):\n${body}`
  }
}

const SIGIL =
  '<!-- GENERATED by LF — do not edit; re-run `literate weave`.\n' +
  '     Customise via `.literate/extensions/` (survives weave).\n' +
  '     See ADR-024 §3 + ADR-026 §3 for the contract. -->'

const PREAMBLE = `# LITERATE.md — Protocol prose

> **LF-the-framework performs no AI work.** Tangle, weave, and
> explain/check are mechanical operations executed by the
> \`literate\` CLI. AI-driven authoring (the prose ↔ code work)
> happens inside the consumer's authoring sessions, enacted by
> the consumer's agent under the Protocol prose below.

This file is materialised by \`literate weave\` from the Tropes
and Concepts vendored under \`.literate/tropes/\` and
\`.literate/concepts/\`, merged with consumer customisations under
\`.literate/extensions/\`. Direct edits to this file do not
survive the next weave; customise via \`.literate/extensions/\`
or by editing the vendored sources.

The consumer's Product-register prose (ADRs about what they're
building, specs, sessions, etc.) lives in \`corpus/\`. This file
covers the **Protocol** register only.
`

// The bundled Trope registry (ADR-026 §4). Adding a bundled Trope
// means one entry here plus one re-export in `trope-bindings.ts`.
const TROPE_REGISTRY: Readonly<Record<string, AnyTrope>> = {
  'session-start': sessionStartTrope,
  'session-end': sessionEndTrope,
}

interface SeedFiles {
  readonly id: string
  readonly prose?: string
  readonly source: 'vendored' | 'extension'
}

const readMaybe = (
  p: string,
): Effect.Effect<string | undefined, never> =>
  Effect.tryPromise({
    try: () => fs.readFile(p, 'utf8'),
    catch: () => undefined,
  }).pipe(Effect.catchAll(() => Effect.succeed(undefined)))

const seedProseFile = (kind: SeedKind): string =>
  kind === 'tropes' ? 'trope.mdx' : 'concept.mdx'

const readSeed = (
  repoRoot: string,
  base: string,
  kind: SeedKind,
  id: string,
  source: 'vendored' | 'extension',
): Effect.Effect<SeedFiles, never> =>
  Effect.gen(function* () {
    const dir = path.join(repoRoot, base, kind, id)
    const prose = yield* readMaybe(path.join(dir, seedProseFile(kind)))
    return {
      id,
      ...(prose !== undefined ? { prose } : {}),
      source,
    }
  })

const listExtensionIds = (
  repoRoot: string,
  kind: SeedKind,
): Effect.Effect<ReadonlyArray<string>, never> =>
  Effect.tryPromise({
    try: async () => {
      const dir = path.join(repoRoot, '.literate', 'extensions', kind)
      const entries = await fs.readdir(dir, { withFileTypes: true })
      return entries.filter((e) => e.isDirectory()).map((e) => e.name)
    },
    catch: () => [] as ReadonlyArray<string>,
  }).pipe(Effect.catchAll(() => Effect.succeed([] as ReadonlyArray<string>)))

const sectionFromSeed = (kind: SeedKind, seed: SeedFiles): string => {
  const heading = `### \`${seed.id}\``
  const body = seed.prose ?? `*(prose missing — ${kind}/${seed.id})*`
  // Strip the body's leading H1 (every seed body begins with a
  // single H1 line; that heading is internal to the file and does
  // not belong in the woven hierarchy under `### \`<id>\``) and
  // demote remaining headings by 2 levels (H2 → H4, H3 → H5, …)
  // so the woven structure reads as `## Concepts` → `### <id>` →
  // `#### <subsection>` cleanly. Demotion is fence-aware: `#`
  // characters inside ``` code blocks are unmodified.
  const stripped = stripLeadingH1(body)
  const demoted = demoteHeadings(stripped, 2)
  return `${heading}\n\n${demoted}\n`
}

const stripLeadingH1 = (src: string): string => {
  const lines = src.split('\n')
  // Skip leading blank lines.
  let i = 0
  while (i < lines.length && lines[i]!.trim() === '') i++
  if (i >= lines.length) return src
  if (!/^#\s+/.test(lines[i]!)) return src
  // Drop the H1 line + a single immediately-following blank, if
  // present.
  const rest = lines.slice(i + 1)
  if (rest[0] === '') return rest.slice(1).join('\n')
  return rest.join('\n')
}

const demoteHeadings = (src: string, levels: number): string => {
  const lines = src.split('\n')
  let inFence = false
  return lines
    .map((line) => {
      if (/^```/.test(line)) {
        inFence = !inFence
        return line
      }
      if (inFence) return line
      return line.replace(/^(#{1,6})(\s)/, (_, h, ws) =>
        '#'.repeat(Math.min((h as string).length + levels, 6)) + ws,
      )
    })
    .join('\n')
}

// Defensive strip of the ADR-024 §3 generated-file sigil before
// parsing authored prose. Authored seeds never carry it; this lets
// consumers paste a sigilled file without a false-positive schema
// failure.
const SIGIL_PREFIX_RE = /^\s*<!--\s*GENERATED by LF[\s\S]*?-->\s*/

const stripSigil = (source: string): string =>
  source.replace(SIGIL_PREFIX_RE, '')

const mdxProcessor = unified()
  .use(remarkParse)
  .use(remarkMdx)
  .use(remarkDirective)

const formatParseIssue = (issue: unknown): string => {
  if (issue instanceof Error) return issue.message
  if (typeof issue === 'string') return issue
  try {
    return JSON.stringify(issue)
  } catch {
    return String(issue)
  }
}

const validateTropeProse = (
  trope: AnyTrope,
  relPath: string,
  proseSource: string,
): ProseSchemaViolation | null => {
  const tree = mdxProcessor.parse(stripSigil(proseSource))
  const result = Schema.decodeUnknownEither(trope.proseSchema)(tree)
  if (Either.isRight(result)) return null
  return {
    _tag: 'ProseSchemaViolation',
    tropeId: trope.id,
    path: relPath,
    expected: `prose conforming to ${trope.id}.proseSchema`,
    got: formatParseIssue(result.left),
  }
}

export interface WeaverServiceShape {
  readonly weave: (
    repoRoot: string,
  ) => Effect.Effect<
    WeaveResult,
    WeaveIOError | ProseSchemaViolations | ManifestReadError
  >
}

export class WeaverService extends Context.Tag(
  '@literate/cli/WeaverService',
)<WeaverService, WeaverServiceShape>() {}

// Pure program that requires ManifestService. WeaverServiceLive
// provides itself (the service method body IS this program); kept
// as a standalone export so verbs can compose without resolving the
// service if they already hold the dependency graph.
export const weaveProgram = (
  repoRoot: string,
): Effect.Effect<
  WeaveResult,
  WeaveIOError | ProseSchemaViolations | ManifestReadError,
  ManifestService
> =>
  Effect.gen(function* () {
    const manifestSvc = yield* ManifestService
    const manifest = yield* manifestSvc.read(repoRoot)
    const tropeEntries = manifest.vendored.filter((e) => e.kind === 'tropes')
    const conceptEntries = manifest.vendored.filter(
      (e) => e.kind === 'concepts',
    )

    // Vendored Tropes/Concepts.
    const vendoredTropes: SeedFiles[] = []
    for (const e of tropeEntries) {
      vendoredTropes.push(
        yield* readSeed(repoRoot, '.literate', 'tropes', e.id, 'vendored'),
      )
    }
    const vendoredConcepts: SeedFiles[] = []
    for (const e of conceptEntries) {
      vendoredConcepts.push(
        yield* readSeed(repoRoot, '.literate', 'concepts', e.id, 'vendored'),
      )
    }

    // Prose-schema validation pass — vendored Tropes only (consumer
    // extensions are outside LF's bundled schema registry). Collect
    // all violations; raise together; block any write on failure.
    const violations: ProseSchemaViolation[] = []
    for (const seed of vendoredTropes) {
      const trope = TROPE_REGISTRY[seed.id]
      if (!trope) continue
      if (seed.prose === undefined) {
        violations.push({
          _tag: 'ProseSchemaViolation',
          tropeId: seed.id,
          path: `.literate/tropes/${seed.id}/trope.mdx`,
          expected: 'trope.mdx file present',
          got: 'missing',
        })
        continue
      }
      const violation = validateTropeProse(
        trope,
        `.literate/tropes/${seed.id}/trope.mdx`,
        seed.prose,
      )
      if (violation) violations.push(violation)
    }

    if (violations.length > 0) {
      return yield* new ProseSchemaViolations({ violations })
    }

    // Consumer extensions.
    const extTropeIds = yield* listExtensionIds(repoRoot, 'tropes')
    const extConceptIds = yield* listExtensionIds(repoRoot, 'concepts')
    const extensionTropes: SeedFiles[] = []
    for (const id of extTropeIds) {
      extensionTropes.push(
        yield* readSeed(
          repoRoot,
          '.literate/extensions',
          'tropes',
          id,
          'extension',
        ),
      )
    }
    const extensionConcepts: SeedFiles[] = []
    for (const id of extConceptIds) {
      extensionConcepts.push(
        yield* readSeed(
          repoRoot,
          '.literate/extensions',
          'concepts',
          id,
          'extension',
        ),
      )
    }

    const extImperatives = yield* readMaybe(
      path.join(repoRoot, '.literate', 'extensions', 'imperatives.md'),
    )

    const lines: string[] = [SIGIL, '', PREAMBLE]

    if (vendoredConcepts.length > 0) {
      lines.push('## Concepts', '')
      for (const seed of vendoredConcepts) {
        lines.push(sectionFromSeed('concepts', seed))
      }
    }

    if (vendoredTropes.length > 0) {
      lines.push('## Tropes', '')
      for (const seed of vendoredTropes) {
        lines.push(sectionFromSeed('tropes', seed))
      }
    }

    const hasExtensions =
      extensionTropes.length > 0 ||
      extensionConcepts.length > 0 ||
      extImperatives !== undefined
    if (hasExtensions) {
      lines.push('## Consumer Extensions', '')
      if (extImperatives !== undefined) {
        lines.push('### Additional Mandatory Agent Instructions', '')
        lines.push(extImperatives.trim(), '')
      }
      if (extensionConcepts.length > 0) {
        lines.push('### Concepts', '')
        for (const seed of extensionConcepts) {
          lines.push(sectionFromSeed('concepts', seed))
        }
      }
      if (extensionTropes.length > 0) {
        lines.push('### Tropes', '')
        for (const seed of extensionTropes) {
          lines.push(sectionFromSeed('tropes', seed))
        }
      }
    }

    if (
      vendoredConcepts.length === 0 &&
      vendoredTropes.length === 0 &&
      !hasExtensions
    ) {
      lines.push(
        '## (No Tropes or Concepts vendored)',
        '',
        'Run `literate tangle tropes session-start` (and similar) to ' +
          'vendor seeds from a registry, or place consumer-authored ' +
          'seeds under `.literate/extensions/`.',
        '',
      )
    }

    const literateMdPath = path.join(repoRoot, '.literate', 'LITERATE.md')
    yield* Effect.tryPromise({
      try: async () => {
        await fs.mkdir(path.dirname(literateMdPath), { recursive: true })
        await fs.writeFile(literateMdPath, lines.join('\n'), 'utf8')
      },
      catch: (e) =>
        new WeaveIOError({
          path: literateMdPath,
          reason: e instanceof Error ? e.message : String(e),
        }),
    })

    return {
      literateMdPath,
      tropesIncluded: [
        ...vendoredTropes.map((s) => `vendored:${s.id}`),
        ...extensionTropes.map((s) => `extension:${s.id}`),
      ],
      conceptsIncluded: [
        ...vendoredConcepts.map((s) => `vendored:${s.id}`),
        ...extensionConcepts.map((s) => `extension:${s.id}`),
      ],
      extensionsIncluded:
        extImperatives !== undefined ? ['imperatives.md'] : [],
    }
  })

export const WeaverServiceLive = Layer.effect(
  WeaverService,
  Effect.gen(function* () {
    const manifestSvc = yield* ManifestService
    return {
      weave: (repoRoot) =>
        weaveProgram(repoRoot).pipe(
          Effect.provideService(ManifestService, manifestSvc),
        ),
    }
  }),
)

export type { ManifestEntry }
