/**
 * Weave engine — materialise `.literate/LITERATE.md` from the
 * vendored Trope/Concept tree plus consumer extensions.
 *
 * Mechanical and deterministic per ADR-025 §2: no AI reasoning,
 * inputs-only, idempotent. Reads the manifest to know what's
 * vendored; reads `.literate/extensions/` for consumer additions;
 * writes `.literate/LITERATE.md` atomically with the sigil from
 * ADR-024 §3.
 */
import * as fs from 'node:fs/promises'
import * as path from 'node:path'

import { readManifest, type ManifestEntry, type SeedKind } from '../registry/manifest.ts'

export interface WeaveResult {
  readonly literateMdPath: string
  readonly tropesIncluded: ReadonlyArray<string>
  readonly conceptsIncluded: ReadonlyArray<string>
  readonly extensionsIncluded: ReadonlyArray<string>
}

const SIGIL =
  '<!-- GENERATED by LF — do not edit; re-run `literate weave`.\n' +
  '     Customise via `.literate/extensions/` (survives weave).\n' +
  '     See ADR-024 §3 + ADR-026 §3 for the contract. -->'

const PREAMBLE = `# LITERATE.md — Protocol prose

> **LF-the-framework performs no AI work.** Tangle, weave, and
> explain/check are mechanical operations executed by the
> \`literate\` CLI. AI-driven authoring (the prose ↔ code work)
> happens inside the consumer's authoring sessions, enacted by
> the consumer's agent under the Protocol prose below.

This file is materialised by \`literate weave\` from the Tropes
and Concepts vendored under \`.literate/tropes/\` and
\`.literate/concepts/\`, merged with consumer customisations under
\`.literate/extensions/\`. Direct edits to this file do not
survive the next weave; customise via \`.literate/extensions/\`
or by editing the vendored sources.

The consumer's Product-register prose (ADRs about what they're
building, specs, sessions, etc.) lives in \`corpus/\`. This file
covers the **Protocol** register only.
`

interface SeedFiles {
  readonly id: string
  readonly prose?: string
  readonly readme?: string
  readonly source: 'vendored' | 'extension'
}

const readMaybe = async (p: string): Promise<string | undefined> => {
  try {
    return await fs.readFile(p, 'utf8')
  } catch {
    return undefined
  }
}

const seedProseFile = (kind: SeedKind): string =>
  kind === 'tropes' ? 'prose.mdx' : 'concept.mdx'

const readSeed = async (
  repoRoot: string,
  base: string,
  kind: SeedKind,
  id: string,
  source: 'vendored' | 'extension',
): Promise<SeedFiles> => {
  const dir = path.join(repoRoot, base, kind, id)
  const prose = await readMaybe(path.join(dir, seedProseFile(kind)))
  const readme = await readMaybe(path.join(dir, 'README.md'))
  return {
    id,
    ...(prose !== undefined ? { prose } : {}),
    ...(readme !== undefined ? { readme } : {}),
    source,
  }
}

const listExtensionIds = async (
  repoRoot: string,
  kind: SeedKind,
): Promise<ReadonlyArray<string>> => {
  const dir = path.join(repoRoot, '.literate', 'extensions', kind)
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true })
    return entries.filter((e) => e.isDirectory()).map((e) => e.name)
  } catch {
    return []
  }
}

const sectionFromSeed = (kind: SeedKind, seed: SeedFiles): string => {
  const heading = `### \`${seed.id}\``
  const intro = seed.readme
    ? seed.readme
        .split('\n')
        .filter((l, i) => i > 0 && !l.startsWith('# '))
        .join('\n')
        .trim()
    : ''
  const body = seed.prose ?? `*(prose missing — ${kind}/${seed.id})*`
  const introBlock = intro ? `${intro}\n\n` : ''
  return `${heading}\n\n${introBlock}${body}\n`
}

export const weave = async (repoRoot: string): Promise<WeaveResult> => {
  const manifest = await readManifest(repoRoot)
  const tropeEntries = manifest.vendored.filter((e) => e.kind === 'tropes')
  const conceptEntries = manifest.vendored.filter(
    (e) => e.kind === 'concepts',
  )

  // Vendored Tropes/Concepts.
  const vendoredTropes: SeedFiles[] = []
  for (const e of tropeEntries) {
    vendoredTropes.push(
      await readSeed(repoRoot, '.literate', 'tropes', e.id, 'vendored'),
    )
  }
  const vendoredConcepts: SeedFiles[] = []
  for (const e of conceptEntries) {
    vendoredConcepts.push(
      await readSeed(repoRoot, '.literate', 'concepts', e.id, 'vendored'),
    )
  }

  // Consumer extensions.
  const extTropeIds = await listExtensionIds(repoRoot, 'tropes')
  const extConceptIds = await listExtensionIds(repoRoot, 'concepts')
  const extensionTropes: SeedFiles[] = []
  for (const id of extTropeIds) {
    extensionTropes.push(
      await readSeed(repoRoot, '.literate/extensions', 'tropes', id, 'extension'),
    )
  }
  const extensionConcepts: SeedFiles[] = []
  for (const id of extConceptIds) {
    extensionConcepts.push(
      await readSeed(repoRoot, '.literate/extensions', 'concepts', id, 'extension'),
    )
  }

  const extImperatives = await readMaybe(
    path.join(repoRoot, '.literate', 'extensions', 'imperatives.md'),
  )

  const lines: string[] = [SIGIL, '', PREAMBLE]

  if (vendoredConcepts.length > 0) {
    lines.push('## Concepts', '')
    for (const seed of vendoredConcepts) {
      lines.push(sectionFromSeed('concepts', seed))
    }
  }

  if (vendoredTropes.length > 0) {
    lines.push('## Tropes', '')
    for (const seed of vendoredTropes) {
      lines.push(sectionFromSeed('tropes', seed))
    }
  }

  const hasExtensions =
    extensionTropes.length > 0 ||
    extensionConcepts.length > 0 ||
    extImperatives !== undefined
  if (hasExtensions) {
    lines.push('## Consumer Extensions', '')
    if (extImperatives !== undefined) {
      lines.push('### Additional Mandatory Agent Instructions', '')
      lines.push(extImperatives.trim(), '')
    }
    if (extensionConcepts.length > 0) {
      lines.push('### Concepts', '')
      for (const seed of extensionConcepts) {
        lines.push(sectionFromSeed('concepts', seed))
      }
    }
    if (extensionTropes.length > 0) {
      lines.push('### Tropes', '')
      for (const seed of extensionTropes) {
        lines.push(sectionFromSeed('tropes', seed))
      }
    }
  }

  if (
    vendoredConcepts.length === 0 &&
    vendoredTropes.length === 0 &&
    !hasExtensions
  ) {
    lines.push(
      '## (No Tropes or Concepts vendored)',
      '',
      'Run `literate tangle tropes session-start` (and similar) to ' +
        'vendor seeds from a registry, or place consumer-authored ' +
        'seeds under `.literate/extensions/`.',
      '',
    )
  }

  const literateMdPath = path.join(repoRoot, '.literate', 'LITERATE.md')
  await fs.mkdir(path.dirname(literateMdPath), { recursive: true })
  await fs.writeFile(literateMdPath, lines.join('\n'), 'utf8')

  return {
    literateMdPath,
    tropesIncluded: [
      ...vendoredTropes.map((s) => `vendored:${s.id}`),
      ...extensionTropes.map((s) => `extension:${s.id}`),
    ],
    conceptsIncluded: [
      ...vendoredConcepts.map((s) => `vendored:${s.id}`),
      ...extensionConcepts.map((s) => `extension:${s.id}`),
    ],
    extensionsIncluded: extImperatives !== undefined ? ['imperatives.md'] : [],
  }
}

export type { ManifestEntry }
