/**
 * Tagged errors for `@literate/cli` (ADR-028).
 *
 * Every throw site in the CLI surfaces as an `Effect` error channel
 * carrying one of these `Data.TaggedError` classes. Per ADR-030 the
 * argv-boundary errors (`UsageError`, `UnknownVerb`, `UnknownKind`)
 * are gone — `@effect/cli`'s `ValidationError` shape replaces them
 * (`Args.choice` rejects unknown kinds; the dispatcher rejects
 * unknown subcommands; per-verb usage is generated by `@effect/cli`).
 *
 * Grouped by concern:
 *
 *   - Template lookup (`UnknownTemplate` — kept; the template name
 *     is a free-form string not modelled as `Args.choice`).
 *   - Config / manifest / fetcher errors under `src/registry/`
 *     (`ConfigParseError`, `RegistryNotFound`, `NoRegistriesConfigured`,
 *     `ManifestReadError`, `ManifestWriteError`, `NoManifestEntry`,
 *     `RegistryUrlMalformed`, `RegistryFetchFailed`).
 *   - Weave + scaffold errors (`WeaveIOError`, `ScaffoldError`). The
 *     prose-schema aggregate error `ProseSchemaViolations` lives with
 *     the weaver (its value-type `ProseSchemaViolation` is structural
 *     to the weaver's validation loop).
 */
import { Data } from 'effect'

import type { ProseSchemaViolations } from './weaver/weaver.ts'

// ---------------------------------------------------------------------------
// Template lookup

export class UnknownTemplate extends Data.TaggedError('UnknownTemplate')<{
  readonly template: string
  readonly available: ReadonlyArray<string>
}> {
  override get message(): string {
    return `init: unknown template '${this.template}'; available: ${this.available.join(', ')}`
  }
}

// ---------------------------------------------------------------------------
// Config / manifest

export class ConfigParseError extends Data.TaggedError('ConfigParseError')<{
  readonly path: string
  readonly reason: string
}> {
  override get message(): string {
    return `literate.json at ${this.path}: ${this.reason}`
  }
}

export class RegistryNotFound extends Data.TaggedError('RegistryNotFound')<{
  readonly name: string
  readonly available: ReadonlyArray<string>
}> {
  override get message(): string {
    return `literate.json: no registry named '${this.name}'. Available: ${this.available.join(', ')}`
  }
}

export class NoRegistriesConfigured extends Data.TaggedError(
  'NoRegistriesConfigured',
) {
  override get message(): string {
    return `literate.json: no registries configured`
  }
}

export class ManifestReadError extends Data.TaggedError('ManifestReadError')<{
  readonly path: string
  readonly reason: string
}> {
  override get message(): string {
    return `${this.path}: ${this.reason}`
  }
}

export class ManifestWriteError extends Data.TaggedError(
  'ManifestWriteError',
)<{
  readonly path: string
  readonly reason: string
}> {
  override get message(): string {
    return `${this.path}: ${this.reason}`
  }
}

export class NoManifestEntry extends Data.TaggedError('NoManifestEntry')<{
  readonly kind: string
  readonly id: string
}> {
  override get message(): string {
    return `update: ${this.kind}/${this.id} is not in .literate/manifest.json — run \`literate tangle\` first`
  }
}

// ---------------------------------------------------------------------------
// Fetcher

export class RegistryUrlMalformed extends Data.TaggedError(
  'RegistryUrlMalformed',
)<{
  readonly url: string
  readonly reason: string
}> {
  override get message(): string {
    return `Registry url '${this.url}': ${this.reason}`
  }
}

export class RegistryFetchFailed extends Data.TaggedError(
  'RegistryFetchFailed',
)<{
  readonly url: string
  readonly reason: string
}> {
  override get message(): string {
    return `Registry fetch failed: ${this.url} — ${this.reason}`
  }
}

// ---------------------------------------------------------------------------
// Weave / scaffold side-effects

export class WeaveIOError extends Data.TaggedError('WeaveIOError')<{
  readonly path: string
  readonly reason: string
}> {
  override get message(): string {
    return `weave: I/O error at ${this.path}: ${this.reason}`
  }
}

export class ScaffoldError extends Data.TaggedError('ScaffoldError')<{
  readonly target: string
  readonly reason: string
}> {
  override get message(): string {
    return `init: scaffold at ${this.target}: ${this.reason}`
  }
}

export class BootstrapSessionFailed extends Data.TaggedError(
  'BootstrapSessionFailed',
)<{
  readonly target: string
  readonly sessionPath: string
  readonly reason: string
}> {
  override get message(): string {
    return `init: bootstrap session-end failed for ${this.sessionPath} (target ${this.target}): ${this.reason}`
  }
}

// ---------------------------------------------------------------------------
// VerbError — union of everything a CLI-owned verb program can surface.
// `ProseSchemaViolations` is structurally an aggregate type and lives
// with the weaver (`src/weaver/weaver.ts`); it is listed here so the
// weaver-composing verbs' error channels are assignable to `VerbError`
// without a circular import. The type is re-declared here verbatim;
// the identity comparison is by `_tag`.

export type VerbError =
  | UnknownTemplate
  | ConfigParseError
  | RegistryNotFound
  | NoRegistriesConfigured
  | ManifestReadError
  | ManifestWriteError
  | NoManifestEntry
  | RegistryUrlMalformed
  | RegistryFetchFailed
  | WeaveIOError
  | ScaffoldError
  | BootstrapSessionFailed
  | ProseSchemaViolations
