/**
 * End-to-end smoke test — the P2 acceptance gate.
 *
 * Exercises the full v0.1 verb chain with the LF repo's own
 * `registry/` as a `file://` registry source:
 *
 *   1. `runInit` scaffolds + tangles `tropes/session-start` +
 *      `tropes/session-end` from the local registry, writes
 *      `literate.json` + `.literate/manifest.json`, runs the
 *      initial weave that produces `.literate/LITERATE.md`.
 *   2. The vendored seeds + weave outputs are inspected.
 *   3. A `Status: Planned` session log is planted in the
 *      scaffolded `corpus/sessions/`.
 *   4. `runContinue` is dispatched against the scratch repo with
 *      a scripted gate that Accepts the Goal.
 *   5. The session log is finalised with terminal sections and
 *      the Goal is upgraded to Completed.
 *   6. `runClose` stamps Closed (…) atomically.
 *   7. `runUpdate` re-fetches the session-start seed and
 *      overwrites the vendored copy (no-op content-wise; verifies
 *      the round trip).
 */
import { afterAll, beforeAll, describe, expect, test } from 'bun:test'
import * as fs from 'node:fs/promises'
import * as os from 'node:os'
import * as path from 'node:path'
import { Effect, Layer } from 'effect'

import { makeScriptedTerminalIO } from '@literate/core'

import {
  ConfigServiceLive,
  FetcherServiceLive,
  ManifestServiceLive,
  runClose,
  runContinue,
  runInit,
  runUpdate,
  WeaverServiceLive,
} from '../index.ts'

const RegistryLayers = Layer.mergeAll(
  ConfigServiceLive,
  ManifestServiceLive,
  FetcherServiceLive,
)
const CliServicesLive = Layer.merge(
  RegistryLayers,
  WeaverServiceLive.pipe(Layer.provide(ManifestServiceLive)),
)

// Resolve the LF repo root (this test file lives at
// packages/cli/src/__tests__/) so we can use it as a `file://`
// registry source.
const LF_REPO_ROOT = path.resolve(__dirname, '..', '..', '..', '..')

const plannedLog = `# Session: 2099-01-01 — bootstrap

**Date:** 2099-01-01
**Started:** —
**Status:** Planned
**Chapter:** —
**Agent:** —

## Goals

### Goal 1 — Establish the bootstrap

**Status:** (provisional)
**Category:** (provisional)
**Topic:** A smoke-test goal — exercise the Planned-path gate and
confirm that the Status / Category fields are rewritten on Accept.

**Upstream:**

- The e2e smoke harness.

**Acceptance:**

- The CLI opens the session and gates this Goal through Accept.
`

describe('@literate/cli e2e — init + continue + close + update', () => {
  let tmp = ''

  beforeAll(async () => {
    tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'lf-e2e-'))
  })

  afterAll(async () => {
    if (tmp) await fs.rm(tmp, { recursive: true, force: true })
  })

  test('init scaffolds, tangles registry seeds, weaves LITERATE.md', async () => {
    const initResult = await Effect.runPromise(
      runInit({
        target: tmp,
        template: 'minimal',
        registryUrl: `file://${LF_REPO_ROOT}`,
        registryRef: 'main',
        seeds: [
          { kind: 'tropes', id: 'session-start' },
          { kind: 'tropes', id: 'session-end' },
        ],
      }).pipe(Effect.provide(CliServicesLive)),
    )

    expect(initResult.target).toBe(tmp)
    expect(initResult.tangled).toEqual([
      { kind: 'tropes', id: 'session-start' },
      { kind: 'tropes', id: 'session-end' },
    ])

    // literate.json was written.
    const config = JSON.parse(
      await fs.readFile(path.join(tmp, 'literate.json'), 'utf8'),
    )
    expect(config.registries[0].name).toBe('literate')
    expect(config.registries[0].url).toBe(`file://${LF_REPO_ROOT}`)

    // .literate/manifest.json carries both seeds.
    const manifest = JSON.parse(
      await fs.readFile(
        path.join(tmp, '.literate', 'manifest.json'),
        'utf8',
      ),
    )
    expect(manifest.$schema).toBe('literate-manifest/v0')
    expect(manifest.vendored).toHaveLength(2)
    expect(manifest.vendored[0].id).toBe('session-start')
    expect(manifest.vendored[0].registry).toBe('literate')

    // The vendored Trope files are present at .literate/tropes/<id>/.
    for (const id of ['session-start', 'session-end']) {
      for (const f of ['index.ts', 'prose.mdx', 'README.md']) {
        const p = path.join(tmp, '.literate', 'tropes', id, f)
        const content = await fs.readFile(p, 'utf8')
        expect(content.length).toBeGreaterThan(0)
      }
    }

    // .literate/LITERATE.md was woven.
    const literateMd = await fs.readFile(initResult.literateMdPath, 'utf8')
    expect(literateMd).toContain('GENERATED by LF')
    expect(literateMd).toContain('LF-the-framework performs no AI work')
    expect(literateMd).toContain('## Tropes')
    expect(literateMd).toContain('### `session-start`')
    expect(literateMd).toContain('### `session-end`')

    // .literate/extensions/.keep survives.
    await fs.access(path.join(tmp, '.literate', 'extensions', '.keep'))

    // CLAUDE.md repo-root pointer survives.
    const claudeMd = await fs.readFile(path.join(tmp, 'CLAUDE.md'), 'utf8')
    expect(claudeMd).toContain('.literate/LITERATE.md')
  })

  test('continue + close — Planned-path gate stamps the Goal Active and Closed', async () => {
    // Plant a Planned session log.
    const relLogPath = 'corpus/sessions/2099-01-01T1200-bootstrap.md'
    const absLogPath = path.join(tmp, relLogPath)
    await fs.writeFile(absLogPath, plannedLog, 'utf8')
    const indexPath = path.join(tmp, 'corpus/sessions/sessions.md')
    const indexBefore = await fs.readFile(indexPath, 'utf8')
    await fs.writeFile(
      indexPath,
      indexBefore +
        `| [2099-01-01T1200-bootstrap.md](./2099-01-01T1200-bootstrap.md) | Bootstrap | Planned |\n`,
      'utf8',
    )

    // runContinue with scripted Accept.
    const { io, writes } = makeScriptedTerminalIO(['a'])
    const ref = await Effect.runPromise(
      runContinue({
        repoRoot: tmp,
        agent: 'e2e-smoke-agent',
        io,
      }),
    )
    expect(ref.path).toBe(relLogPath)
    expect(ref.slug).toBe('bootstrap')
    expect(writes.join('')).toContain('Review draft')

    const opened = await fs.readFile(absLogPath, 'utf8')
    expect(opened).toContain('**Status:** Open')
    expect(opened).toContain('**Agent:** e2e-smoke-agent')
    expect(opened).toContain('**Status:** Active')
    expect(opened).toContain('**Category:** feature')
    expect(opened).toContain('## Pre-work')
    expect(opened).toContain('## Execution Log')
    expect(opened).toMatch(/"stepId":"session-start/)

    // Populate terminal sections; upgrade to Completed.
    const closeReady = opened
      .replace('**Status:** Active', '**Status:** Completed')
      .concat(
        `\n## Decisions Made\n\n- No decisions this session.\n` +
          `\n## Work Done\n\n- Smoke-tested the open-and-close lifecycle.\n` +
          `\n## Deferred / Discovered\n\n- none.\n` +
          `\n## Summary\n\nSmoke test passed — open, gate, close end-to-end.\n`,
      )
    await fs.writeFile(absLogPath, closeReady, 'utf8')

    // runClose stamps Closed (…).
    const closure = await Effect.runPromise(
      runClose({ repoRoot: tmp, sessionPath: relLogPath }),
    )
    expect(closure.closedAt).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/)
    const closed = await fs.readFile(absLogPath, 'utf8')
    expect(closed).toContain(`**Status:** Closed (${closure.closedAt})`)
    const indexAfter = await fs.readFile(indexPath, 'utf8')
    expect(indexAfter).toContain(`Closed (${closure.closedAt})`)
  })

  test('update re-fetches a vendored seed and bumps its fetchedAt', async () => {
    // Mutate a vendored file so update overwrites it.
    const vendoredProse = path.join(
      tmp,
      '.literate',
      'tropes',
      'session-start',
      'prose.mdx',
    )
    const original = await fs.readFile(vendoredProse, 'utf8')
    await fs.writeFile(vendoredProse, original + '\n<!-- consumer edit -->\n', 'utf8')

    const before = JSON.parse(
      await fs.readFile(path.join(tmp, '.literate', 'manifest.json'), 'utf8'),
    )
    const beforeFetched = before.vendored.find(
      (e: { id: string }) => e.id === 'session-start',
    ).fetchedAt

    // Add a tiny artificial delay so the fetchedAt changes.
    await new Promise((r) => setTimeout(r, 10))

    const result = await Effect.runPromise(
      runUpdate({
        repoRoot: tmp,
        kind: 'tropes',
        id: 'session-start',
      }).pipe(Effect.provide(CliServicesLive)),
    )
    expect(result.entry.id).toBe('session-start')
    expect(result.entry.fetchedAt).not.toBe(beforeFetched)
    expect(result.overwritten).toContain(
      '.literate/tropes/session-start/prose.mdx',
    )

    // The consumer edit was wiped — file is back to canonical.
    const refreshed = await fs.readFile(vendoredProse, 'utf8')
    expect(refreshed).toBe(original)
  })
})
